### ISSUE TITLE
[Bug]: 403 Forbidden

### ISSUE THREAD

**Issue by godlockin** [vzhd1701/enex2notion#76] opened 2023-02-14 03:17 UTC
### enex2notion version

0.2.25

### What OS are you using?

MacOS

### OS Version / Linux distribution

-

### Bug description

I followed the guidance of how to get token & restore enex into notion in readme.md. The first some notes' recovery are success but after a while it failed with exception of 403. i tried to log out & login notion and take a new token, but the issue happens again. 

Any suggestions on this situation?

### Log excerpt

```shell
enex2notion --token $token  --done-file notes.txt $path_to_notes
Traceback (most recent call last):
  File "/usr/local/bin/enex2notion", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/enex2notion/cli.py", line 47, in main
    cli(sys.argv[1:])
  File "/usr/local/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/enex2notion/cli.py", line 26, in cli
    root = get_root(args.token, args.root_page)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/enex2notion/cli_notion.py", line 21, in get_root
    client = get_notion_client(token)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/enex2notion/cli_notion.py", line 31, in get_notion_client
    return NotionClient(token_v2=token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/notion/client.py", line 113, in __init__
    self._update_user_info()
  File "/usr/local/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/notion/client.py", line 144, in _update_user_info
    records = self.post("loadUserContent", {}).json()["recordMap"]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/ratelimit/decorators.py", line 113, in wrapper
    return func(*args, **kargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/ratelimit/decorators.py", line 80, in wrapper
    return func(*args, **kargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/notion/client.py", line 275, in post
    return self._post(endpoint, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/notion/client.py", line 298, in _post
    response.raise_for_status()
  File "/usr/local/Cellar/enex2notion/0.2.25/libexec/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.notion.so/api/v3/loadUserContent
```
```

**Comment by GetoXs** [comment] 2023-05-05 16:46
Duplicate of: https://github.com/vzhd1701/enex2notion/issues/87

**Closed** 2023-05-07 06:44 UTC
Labels: bug
