### ISSUE TITLE
[Bug]: .HTTPError: 403

### ISSUE THREAD

**Issue by darknesshub** [vzhd1701/enex2notion#87] opened 2023-05-02 03:14 UTC
### enex2notion version

0.2.25

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 10

### Bug description

requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.notion.so/api/v3/loadUserContent
[3564] Failed to execute script '__main__' due to unhandled exception!

**Comment by chrisdeniaud** [comment] 2023-05-05 12:24
I'm meeting the same issue whereas token is good because I still use it via web interface.

Same OS and same enex2notion version.

I used it without any problem until last week.

**Comment by vzhd1701** [comment] 2023-05-05 12:59
Can you show the full error log?

**Comment by GetoXs** [comment] 2023-05-05 16:45
Same issue here.
@vzhd1701  FYI. token_v2 start with some prefix `v02%3Auser_token_or_cookies%3AXXXXXX` where `XXXXXX` is rest of the token

**Comment by chrisdeniaud** [comment] 2023-05-05 17:36
The issue is the same when the token hasn't the prefix `v02%3Auser_token_or_cookies`
ex : 
`enex2notion.exe --log e2n.log --token cexxx.xxxc8 .\Pros.2.enex`

**Comment by darknesshub** [comment] 2023-05-06 02:43
same

**Comment by jerryfan86** [comment] 2023-05-06 06:52
same

**Comment by vzhd1701** [comment] 2023-05-06 08:32
This should be fixed now. Please check out the latest version.

**Comment by chrisdeniaud** [comment] 2023-05-06 10:30
v0.2.26 works!
Thank you @vzhd1701 !!!

**Closed** 2023-05-07 06:45 UTC
Labels: bug
